### ISSUE TITLE
FEES: Algorithmic Core Pool Selection in bal_addresses

### ISSUE THREAD

**Issue by Tritium-VLK** [BalancerMaxis/bal_addresses#176]
Right now we have a static list of core pools that is challenging to keep up to date.  The goal is to move to automatically selecting core pools based on some parameters.  There should additionally be a blacklist that excludes pools explicitly and a whitelist that includes them. 

core pool =

1: At least 50% IB token
1a: Has rate provider on IB token
1b: Yield fees are not exempt
2: IB token yields at least 2.5% (nice to have but not critical/can be handled with blacklist for now)
3: Has over 300k in liquidity (kinda also just made this up, no 0s)
4: Is on the whitelist (this is an or condition while the others are and)

Further, anything on the blacklist should be excluded until it is no longer on the blacklist.

**Comment by SHAKOTN** [comment]
There was a problem today with new wzeth pool on mainnet. While pool is live and considered "core", it's still not visible in subgraphs and API. Not sure if this can impact your work here but still

**Comment by gosuto-inzasheru** [comment]
hmm well the code in #177 wont pick up on it yet then, since it uses the subgraph as main source of data
