### ISSUE TITLE
Auto Core pool list issues

### ISSUE THREAD

**Issue by Tritium-VLK** [BalancerMaxis/bal_addresses#214]
- wjAURA has a dead rate provider and just needs to be blacklisted
- Pools with less than 50% interest bearing tokens like the gold pools are appearing on the list.
- Need to check delta with current list again and figure out differences

Need to be more careful when reintroducing.

We have reverted back to using the core pools list on multisig ops.  The resulting list should match, and at best we should watch that it continues to match for a while before trying another cutover.

**Comment by gosuto-inzasheru** [comment]
TODO: add (alphabetical) sorting, to minimise diffs
