### ISSUE TITLE
Add FTM BEETs vesting contract to bal_addresses

### ISSUE THREAD

**Issue by Xeonus** [BalancerMaxis/bal_addresses#216]
- Add support for FTM chain -> do we need to do that?
- Add the FTM BEETs vesting contract to fantom: https://ftmscan.com/address/0x8d381ec09356c3f1805c54b2bb0867e8b417dc3a#readContract
- Beneficiary is a new DAO wallet on FTM: 0xFe2022da08d17ac8388F5bEFE4F71456255105A4

**Comment by gosuto-inzasheru** [comment]
solved via https://github.com/BalancerMaxis/bal_addresses/pull/264
