### ISSUE TITLE
Configure Maxi brownie to support new chains

### ISSUE THREAD

**Issue by Tritium-VLK** [BalancerMaxis/bal_addresses#292]

**Comment by Tritium-VLK** [comment]
Make maxi brownie fork work with Mode, Linea and Fraxtal (fraxtal is less eminent).  Should need to add RPC, and setup a way to pull in the scanner keys from environment variables.

**Comment by gosuto-inzasheru** [comment]
@Tritium-VLK this is fixed in https://github.com/BalancerMaxis/brownie/tree/v1.20.x no?
